apiVersion: apps/v1
kind: Deployment
metadata:
  name: bookinfo-dev-details
  namespace: bookinfo-dev
  labels:
    app: bookinfo-dev-details
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bookinfo-dev-details
  template:
    metadata:
      labels:
        app: bookinfo-dev-details
    spec:
      containers:
      - name: bookinfo-dev-details
        image: asia.gcr.io/river-howl-327208/bookinfo-details:dev
        imagePullPolicy: Always
        ports:
        - containerPort: 9080
          name: web-port
          protocol: TCP
        livenessProbe:
          httpGet:
            path: /health
            port: 9080
            scheme: HTTP
        readinessProbe:
          httpGet:
            path: /health
            port: 9080
            scheme: HTTP
        # env:
        # - name: SERVICE_VERSION
        #   value: v1
      imagePullSecrets:
      - name: registry-bookinfo