apiVersion: apps/v1
kind: Deployment
metadata:
  name: bookinfo-dev-productpage
  namespace: bookinfo-dev
  labels:
    app: bookinfo-dev-productpage
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bookinfo-dev-productpage
  template:
    metadata:
      labels:
        app: bookinfo-dev-productpage
    spec:
      containers:
      - name: bookinfo-dev-productpage
        image: asia.gcr.io/river-howl-327208/bookinfo-productpage:dev
        imagePullPolicy: Always
        ports:
        - containerPort: 9080
          name: web-port
          protocol: TCP
        livenessProbe:
          httpGet:
            path: /health
            port: 9080
            scheme: HTTP
        readinessProbe:
          httpGet:
            path: /health
            port: 9080
            scheme: HTTP
        env:
        - name: DETAILS_HOSTNAME
          value: "http://dev.bookinfo.abosszz.com/details"
        - name: RATINGS_HOSTNAME
          value: "http://dev.bookinfo.abosszz.com/ratings"
        - name: REVIEWS_HOSTNAME
          value: "http://dev.bookinfo.abosszz.com/reviews"
      imagePullSecrets:
      - name: registry-bookinfo